#!/bin/bash
# Setup audio routing for system audio capture with volume control

echo "==================================================================="
echo "Audio Routing Setup for ASR Service"
echo "==================================================================="
echo ""
echo "CURRENT ISSUE: Multi-Output Device doesn't support volume control"
echo ""
echo "WORKAROUND OPTIONS:"
echo ""
echo "1. Use external volume control (keyboard, external mixer)"
echo "2. Install 'Background Music' app (free, open-source)"
echo "   - Provides volume control for multi-output setups"
echo "   - Download: https://github.com/kyleneideck/BackgroundMusic"
echo ""
echo "3. Use 'SoundSource' by Rogue Amoeba (paid, but excellent)"
echo "   - Per-app volume control"
echo "   - Routing without Multi-Output Device complexity"
echo "   - Download: https://rogueamoeba.com/soundsource/"
echo ""
echo "4. Use 'Loopback' by Rogue Amoeba (paid)"
echo "   - Professional audio routing"
echo "   - Virtual devices with full control"
echo "   - Download: https://rogueamoeba.com/loopback/"
echo ""
echo "==================================================================="
echo "RECOMMENDED: Background Music (free) or SoundSource (paid)"
echo "==================================================================="
echo ""
